version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "http-lambda-authorizer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-l74rq5rmaojl"
s3_prefix = "http-lambda-authorizer"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = [
"Memory=2048"
]
